// src/constants/pokemonData.js

export const pokemonList = [
  {
    "index": 1,
    "name": "フシギダネ",
    "type1": "くさ",
    "type2": "どく",
    "Ability1": "しんりょく",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "ようりょくそ",
    "hp": 45,
    "attack": 49,
    "defense": 49,
    "specialAttack": 65,
    "specialDefense": 65,
    "speed": 45,
    "total": 318
  },
  {
    "index": 2,
    "name": "フシギソウ",
    "type1": "くさ",
    "type2": "どく",
    "Ability1": "しんりょく",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "ようりょくそ",
    "hp": 60,
    "attack": 62,
    "defense": 63,
    "specialAttack": 80,
    "specialDefense": 80,
    "speed": 60,
    "total": 405
  },
  {
    "index": 3,
    "name": "フシギバナ",
    "type1": "くさ",
    "type2": "どく",
    "Ability1": "しんりょく",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "ようりょくそ",
    "hp": 80,
    "attack": 82,
    "defense": 83,
    "specialAttack": 100,
    "specialDefense": 100,
    "speed": 80,
    "total": 525
  },
  {
    "index": 4,
    "name": "ヒトカゲ",
    "type1": "ほのお",
    "type2": "",
    "Ability1": "もうか",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "サンパワー",
    "hp": 39,
    "attack": 52,
    "defense": 43,
    "specialAttack": 60,
    "specialDefense": 50,
    "speed": 65,
    "total": 309
  },
  {
    "index": 5,
    "name": "リザード",
    "type1": "ほのお",
    "type2": "",
    "Ability1": "もうか",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "サンパワー",
    "hp": 58,
    "attack": 64,
    "defense": 58,
    "specialAttack": 80,
    "specialDefense": 65,
    "speed": 80,
    "total": 405
  },
  {
    "index": 6,
    "name": "リザードン",
    "type1": "ほのお",
    "type2": "ひこう",
    "Ability1": "もうか",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "サンパワー",
    "hp": 78,
    "attack": 84,
    "defense": 78,
    "specialAttack": 109,
    "specialDefense": 85,
    "speed": 100,
    "total": 534
  },
  {
    "index": 7,
    "name": "ゼニガメ",
    "type1": "みず",
    "type2": "",
    "Ability1": "げきりゅう",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "あめうけざら",
    "hp": 44,
    "attack": 48,
    "defense": 65,
    "specialAttack": 50,
    "specialDefense": 64,
    "speed": 43,
    "total": 314
  },
  {
    "index": 8,
    "name": "カメール",
    "type1": "みず",
    "type2": "",
    "Ability1": "げきりゅう",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "あめうけざら",
    "hp": 59,
    "attack": 63,
    "defense": 80,
    "specialAttack": 65,
    "specialDefense": 80,
    "speed": 58,
    "total": 405
  },
  {
    "index": 9,
    "name": "カメックス",
    "type1": "みず",
    "type2": "",
    "Ability1": "げきりゅう",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "あめうけざら",
    "hp": 79,
    "attack": 83,
    "defense": 100,
    "specialAttack": 85,
    "specialDefense": 105,
    "speed": 78,
    "total": 530
  },
  {
    "index": 10,
    "name": "キャタピー",
    "type1": "むし",
    "type2": "",
    "Ability1": "りんぷん",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "にげあし",
    "hp": 45,
    "attack": 30,
    "defense": 35,
    "specialAttack": 20,
    "specialDefense": 20,
    "speed": 45,
    "total": 195
  },
  {
    "index": 11,
    "name": "トランセル",
    "type1": "むし",
    "type2": "",
    "Ability1": "だっぴ",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "",
    "hp": 50,
    "attack": 20,
    "defense": 55,
    "specialAttack": 25,
    "specialDefense": 25,
    "speed": 30,
    "total": 205
  },
  {
    "index": 12,
    "name": "バタフリー",
    "type1": "むし",
    "type2": "ひこう",
    "Ability1": "ふくがん",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "いろめがね",
    "hp": 60,
    "attack": 45,
    "defense": 50,
    "specialAttack": 90,
    "specialDefense": 80,
    "speed": 70,
    "total": 395
  },
  {
    "index": 13,
    "name": "ビードル",
    "type1": "むし",
    "type2": "どく",
    "Ability1": "りんぷん",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "にげあし",
    "hp": 40,
    "attack": 35,
    "defense": 30,
    "specialAttack": 20,
    "specialDefense": 20,
    "speed": 50,
    "total": 195
  },
  {
    "index": 14,
    "name": "コクーン",
    "type1": "むし",
    "type2": "どく",
    "Ability1": "だっぴ",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "",
    "hp": 45,
    "attack": 25,
    "defense": 50,
    "specialAttack": 25,
    "specialDefense": 25,
    "speed": 35,
    "total": 205
  },
  {
    "index": 15,
    "name": "スピアー",
    "type1": "むし",
    "type2": "どく",
    "Ability1": "むしのしらせ",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "スナイパー",
    "hp": 65,
    "attack": 90,
    "defense": 40,
    "specialAttack": 45,
    "specialDefense": 80,
    "speed": 75,
    "total": 395
  },
  {
    "index": 16,
    "name": "ポッポ",
    "type1": "ノーマル",
    "type2": "ひこう",
    "Ability1": "するどいめ",
    "Ability2": "ちどりあし",
    "Ability3": "",
    "HiddenAbility": "はとむね",
    "hp": 40,
    "attack": 45,
    "defense": 40,
    "specialAttack": 35,
    "specialDefense": 35,
    "speed": 56,
    "total": 251
  },
  {
    "index": 17,
    "name": "ピジョン",
    "type1": "ノーマル",
    "type2": "ひこう",
    "Ability1": "するどいめ",
    "Ability2": "ちどりあし",
    "Ability3": "",
    "HiddenAbility": "はとむね",
    "hp": 63,
    "attack": 60,
    "defense": 55,
    "specialAttack": 50,
    "specialDefense": 50,
    "speed": 71,
    "total": 349
  },
  {
    "index": 18,
    "name": "ピジョット",
    "type1": "ノーマル",
    "type2": "ひこう",
    "Ability1": "するどいめ",
    "Ability2": "ちどりあし",
    "Ability3": "",
    "HiddenAbility": "はとむね",
    "hp": 83,
    "attack": 80,
    "defense": 75,
    "specialAttack": 70,
    "specialDefense": 70,
    "speed": 101,
    "total": 479
  },
  {
    "index": 19,
    "name": "コラッタ",
    "type1": "ノーマル",
    "type2": "",
    "Ability1": "にげあし",
    "Ability2": "こんじょう",
    "Ability3": "",
    "HiddenAbility": "はりきり",
    "hp": 30,
    "attack": 56,
    "defense": 35,
    "specialAttack": 25,
    "specialDefense": 35,
    "speed": 72,
    "total": 253
  },
  {
    "index": 20,
    "name": "ラッタ",
    "type1": "ノーマル",
    "type2": "",
    "Ability1": "にげあし",
    "Ability2": "こんじょう",
    "Ability3": "",
    "HiddenAbility": "はりきり",
    "hp": 55,
    "attack": 81,
    "defense": 60,
    "specialAttack": 50,
    "specialDefense": 70,
    "speed": 97,
    "total": 413
  },
  {
    "index": 21,
    "name": "オニスズメ",
    "type1": "ノーマル",
    "type2": "ひこう",
    "Ability1": "するどいめ",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "スナイパー",
    "hp": 40,
    "attack": 60,
    "defense": 30,
    "specialAttack": 31,
    "specialDefense": 31,
    "speed": 70,
    "total": 262
  },
  {
    "index": 22,
    "name": "オニドリル",
    "type1": "ノーマル",
    "type2": "ひこう",
    "Ability1": "するどいめ",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "スナイパー",
    "hp": 65,
    "attack": 90,
    "defense": 65,
    "specialAttack": 61,
    "specialDefense": 61,
    "speed": 100,
    "total": 442
  },
  {
    "index": 23,
    "name": "アーボ",
    "type1": "どく",
    "type2": "",
    "Ability1": "いかく",
    "Ability2": "だっぴ",
    "Ability3": "",
    "HiddenAbility": "きんちょうかん",
    "hp": 35,
    "attack": 60,
    "defense": 44,
    "specialAttack": 40,
    "specialDefense": 54,
    "speed": 55,
    "total": 288
  },
  {
    "index": 24,
    "name": "アーボック",
    "type1": "どく",
    "type2": "",
    "Ability1": "いかく",
    "Ability2": "だっぴ",
    "Ability3": "",
    "HiddenAbility": "きんちょうかん",
    "hp": 60,
    "attack": 95,
    "defense": 69,
    "specialAttack": 65,
    "specialDefense": 79,
    "speed": 80,
    "total": 448
  },
  {
    "index": 25,
    "name": "ピカチュウ",
    "type1": "でんき",
    "type2": "",
    "Ability1": "せいでんき",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "ひらいしん",
    "hp": 35,
    "attack": 55,
    "defense": 40,
    "specialAttack": 50,
    "specialDefense": 50,
    "speed": 90,
    "total": 320
  },
  {
    "index": 26,
    "name": "ライチュウ",
    "type1": "でんき",
    "type2": "",
    "Ability1": "せいでんき",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "ひらいしん",
    "hp": 60,
    "attack": 90,
    "defense": 55,
    "specialAttack": 90,
    "specialDefense": 80,
    "speed": 110,
    "total": 485
  },
  {
    "index": 27,
    "name": "サンド",
    "type1": "じめん",
    "type2": "",
    "Ability1": "すながくれ",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "すなかき",
    "hp": 50,
    "attack": 75,
    "defense": 85,
    "specialAttack": 20,
    "specialDefense": 30,
    "speed": 40,
    "total": 300
  },
  {
    "index": 28,
    "name": "サンドパン",
    "type1": "じめん",
    "type2": "",
    "Ability1": "すながくれ",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "すなかき",
    "hp": 75,
    "attack": 100,
    "defense": 110,
    "specialAttack": 45,
    "specialDefense": 55,
    "speed": 65,
    "total": 450
  },
  {
    "index": 29,
    "name": "ニドラン♀",
    "type1": "どく",
    "type2": "",
    "Ability1": "どくのトゲ",
    "Ability2": "とうそうしん",
    "Ability3": "",
    "HiddenAbility": "はりきり",
    "hp": 55,
    "attack": 47,
    "defense": 52,
    "specialAttack": 40,
    "specialDefense": 40,
    "speed": 41,
    "total": 275
  },
  {
    "index": 30,
    "name": "ニドリーナ",
    "type1": "どく",
    "type2": "",
    "Ability1": "どくのトゲ",
    "Ability2": "とうそうしん",
    "Ability3": "",
    "HiddenAbility": "はりきり",
    "hp": 70,
    "attack": 62,
    "defense": 67,
    "specialAttack": 55,
    "specialDefense": 55,
    "speed": 56,
    "total": 365
  },
  {
    "index": 31,
    "name": "ニドクイン",
    "type1": "どく",
    "type2": "じめん",
    "Ability1": "どくのトゲ",
    "Ability2": "とうそうしん",
    "Ability3": "",
    "HiddenAbility": "ちからずく",
    "hp": 90,
    "attack": 92,
    "defense": 87,
    "specialAttack": 75,
    "specialDefense": 85,
    "speed": 76,
    "total": 505
  },
  {
    "index": 32,
    "name": "ニドラン♂",
    "type1": "どく",
    "type2": "",
    "Ability1": "どくのトゲ",
    "Ability2": "とうそうしん",
    "Ability3": "",
    "HiddenAbility": "はりきり",
    "hp": 46,
    "attack": 57,
    "defense": 40,
    "specialAttack": 40,
    "specialDefense": 40,
    "speed": 50,
    "total": 273
  },
  {
    "index": 33,
    "name": "ニドリーノ",
    "type1": "どく",
    "type2": "",
    "Ability1": "どくのトゲ",
    "Ability2": "とうそうしん",
    "Ability3": "",
    "HiddenAbility": "はりきり",
    "hp": 61,
    "attack": 72,
    "defense": 57,
    "specialAttack": 55,
    "specialDefense": 55,
    "speed": 65,
    "total": 365
  },
  {
    "index": 34,
    "name": "ニドキング",
    "type1": "どく",
    "type2": "じめん",
    "Ability1": "どくのトゲ",
    "Ability2": "とうそうしん",
    "Ability3": "",
    "HiddenAbility": "ちからずく",
    "hp": 81,
    "attack": 102,
    "defense": 77,
    "specialAttack": 85,
    "specialDefense": 75,
    "speed": 85,
    "total": 505
  },
  {
    "index": 35,
    "name": "ピッピ",
    "type1": "フェアリー",
    "type2": "",
    "Ability1": "メロメロボディ",
    "Ability2": "マジックガード",
    "Ability3": "",
    "HiddenAbility": "フレンドガード",
    "hp": 70,
    "attack": 45,
    "defense": 48,
    "specialAttack": 60,
    "specialDefense": 65,
    "speed": 35,
    "total": 323
  },
  {
    "index": 36,
    "name": "ピクシー",
    "type1": "フェアリー",
    "type2": "",
    "Ability1": "メロメロボディ",
    "Ability2": "マジックガード",
    "Ability3": "",
    "HiddenAbility": "てんねん",
    "hp": 95,
    "attack": 70,
    "defense": 73,
    "specialAttack": 95,
    "specialDefense": 90,
    "speed": 60,
    "total": 483
  },
  {
    "index": 37,
    "name": "ロコン",
    "type1": "ほのお",
    "type2": "",
    "Ability1": "もらいび",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "ひでり",
    "hp": 38,
    "attack": 41,
    "defense": 40,
    "specialAttack": 50,
    "specialDefense": 65,
    "speed": 65,
    "total": 299
  },
  {
    "index": 38,
    "name": "キュウコン",
    "type1": "ほのお",
    "type2": "",
    "Ability1": "もらいび",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "ひでり",
    "hp": 73,
    "attack": 76,
    "defense": 75,
    "specialAttack": 81,
    "specialDefense": 100,
    "speed": 100,
    "total": 505
  },
  {
    "index": 39,
    "name": "プリン",
    "type1": "ノーマル",
    "type2": "フェアリー",
    "Ability1": "メロメロボディ",
    "Ability2": "かちき",
    "Ability3": "",
    "HiddenAbility": "フレンドガード",
    "hp": 115,
    "attack": 45,
    "defense": 20,
    "specialAttack": 45,
    "specialDefense": 25,
    "speed": 20,
    "total": 270
  },
  {
    "index": 40,
    "name": "プクリン",
    "type1": "ノーマル",
    "type2": "フェアリー",
    "Ability1": "メロメロボディ",
    "Ability2": "かちき",
    "Ability3": "",
    "HiddenAbility": "おみとおし",
    "hp": 140,
    "attack": 70,
    "defense": 45,
    "specialAttack": 85,
    "specialDefense": 50,
    "speed": 45,
    "total": 435
  },
  {
    "index": 41,
    "name": "ズバット",
    "type1": "どく",
    "type2": "ひこう",
    "Ability1": "せいしんりょく",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "すりぬけ",
    "hp": 40,
    "attack": 45,
    "defense": 35,
    "specialAttack": 30,
    "specialDefense": 40,
    "speed": 55,
    "total": 245
  },
  {
    "index": 42,
    "name": "ゴルバット",
    "type1": "どく",
    "type2": "ひこう",
    "Ability1": "せいしんりょく",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "すりぬけ",
    "hp": 75,
    "attack": 80,
    "defense": 70,
    "specialAttack": 65,
    "specialDefense": 75,
    "speed": 90,
    "total": 455
  },
  {
    "index": 43,
    "name": "ナゾノクサ",
    "type1": "くさ",
    "type2": "どく",
    "Ability1": "ようりょくそ",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "にげあし",
    "hp": 45,
    "attack": 50,
    "defense": 55,
    "specialAttack": 75,
    "specialDefense": 65,
    "speed": 30,
    "total": 320
  },
  {
    "index": 44,
    "name": "クサイハナ",
    "type1": "くさ",
    "type2": "どく",
    "Ability1": "ようりょくそ",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "あくしゅう",
    "hp": 60,
    "attack": 65,
    "defense": 70,
    "specialAttack": 85,
    "specialDefense": 75,
    "speed": 40,
    "total": 395
  },
  {
    "index": 45,
    "name": "ラフレシア",
    "type1": "くさ",
    "type2": "どく",
    "Ability1": "ようりょくそ",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "ほうし",
    "hp": 75,
    "attack": 80,
    "defense": 85,
    "specialAttack": 110,
    "specialDefense": 90,
    "speed": 50,
    "total": 490
  },
  {
    "index": 46,
    "name": "パラス",
    "type1": "むし",
    "type2": "くさ",
    "Ability1": "ほうし",
    "Ability2": "かんそうはだ",
    "Ability3": "",
    "HiddenAbility": "しめりけ",
    "hp": 35,
    "attack": 70,
    "defense": 55,
    "specialAttack": 45,
    "specialDefense": 55,
    "speed": 25,
    "total": 285
  },
  {
    "index": 47,
    "name": "パラセクト",
    "type1": "むし",
    "type2": "くさ",
    "Ability1": "ほうし",
    "Ability2": "かんそうはだ",
    "Ability3": "",
    "HiddenAbility": "しめりけ",
    "hp": 60,
    "attack": 95,
    "defense": 80,
    "specialAttack": 60,
    "specialDefense": 80,
    "speed": 30,
    "total": 405
  },
  {
    "index": 48,
    "name": "コンパン",
    "type1": "むし",
    "type2": "どく",
    "Ability1": "ふくがん",
    "Ability2": "いろめがね",
    "Ability3": "",
    "HiddenAbility": "にげあし",
    "hp": 60,
    "attack": 55,
    "defense": 50,
    "specialAttack": 40,
    "specialDefense": 55,
    "speed": 45,
    "total": 305
  },
  {
    "index": 49,
    "name": "モルフォン",
    "type1": "むし",
    "type2": "どく",
    "Ability1": "りんぷん",
    "Ability2": "いろめがね",
    "Ability3": "",
    "HiddenAbility": "ミラクルスキン",
    "hp": 70,
    "attack": 65,
    "defense": 60,
    "specialAttack": 90,
    "specialDefense": 75,
    "speed": 90,
    "total": 450
  },
  {
    "index": 50,
    "name": "ディグダ",
    "type1": "じめん",
    "type2": "",
    "Ability1": "すながくれ",
    "Ability2": "ありじごく",
    "Ability3": "",
    "HiddenAbility": "すなのちから",
    "hp": 10,
    "attack": 55,
    "defense": 25,
    "specialAttack": 35,
    "specialDefense": 45,
    "speed": 95,
    "total": 265
  },
  {
    "index": 51,
    "name": "ダグトリオ",
    "type1": "じめん",
    "type2": "",
    "Ability1": "すながくれ",
    "Ability2": "ありじごく",
    "Ability3": "",
    "HiddenAbility": "すなのちから",
    "hp": 35,
    "attack": 100,
    "defense": 50,
    "specialAttack": 50,
    "specialDefense": 70,
    "speed": 120,
    "total": 425
  },
  {
    "index": 52,
    "name": "ニャース",
    "type1": "ノーマル",
    "type2": "",
    "Ability1": "ものひろい",
    "Ability2": "テクニシャン",
    "Ability3": "",
    "HiddenAbility": "きんちょうかん",
    "hp": 40,
    "attack": 45,
    "defense": 35,
    "specialAttack": 40,
    "specialDefense": 40,
    "speed": 90,
    "total": 290
  },
  {
    "index": 53,
    "name": "ペルシアン",
    "type1": "ノーマル",
    "type2": "",
    "Ability1": "じゅうなん",
    "Ability2": "テクニシャン",
    "Ability3": "",
    "HiddenAbility": "きんちょうかん",
    "hp": 65,
    "attack": 70,
    "defense": 60,
    "specialAttack": 65,
    "specialDefense": 65,
    "speed": 115,
    "total": 440
  },
  {
    "index": 54,
    "name": "コダック",
    "type1": "みず",
    "type2": "",
    "Ability1": "しめりけ",
    "Ability2": "ノーてんき",
    "Ability3": "",
    "HiddenAbility": "すいすい",
    "hp": 50,
    "attack": 52,
    "defense": 48,
    "specialAttack": 65,
    "specialDefense": 50,
    "speed": 55,
    "total": 320
  },
  {
    "index": 55,
    "name": "ゴルダック",
    "type1": "みず",
    "type2": "",
    "Ability1": "しめりけ",
    "Ability2": "ノーてんき",
    "Ability3": "",
    "HiddenAbility": "すいすい",
    "hp": 80,
    "attack": 82,
    "defense": 78,
    "specialAttack": 95,
    "specialDefense": 80,
    "speed": 85,
    "total": 500
  },
  {
    "index": 56,
    "name": "マンキー",
    "type1": "かくとう",
    "type2": "",
    "Ability1": "やるき",
    "Ability2": "いかりのつぼ",
    "Ability3": "",
    "HiddenAbility": "まけんき",
    "hp": 40,
    "attack": 80,
    "defense": 35,
    "specialAttack": 35,
    "specialDefense": 45,
    "speed": 70,
    "total": 305
  },
  {
    "index": 57,
    "name": "オコリザル",
    "type1": "かくとう",
    "type2": "",
    "Ability1": "やるき",
    "Ability2": "いかりのつぼ",
    "Ability3": "",
    "HiddenAbility": "まけんき",
    "hp": 65,
    "attack": 105,
    "defense": 60,
    "specialAttack": 60,
    "specialDefense": 70,
    "speed": 95,
    "total": 455
  },
  {
    "index": 58,
    "name": "ガーディ",
    "type1": "ほのお",
    "type2": "",
    "Ability1": "いかく",
    "Ability2": "もらいび",
    "Ability3": "",
    "HiddenAbility": "せいぎのこころ",
    "hp": 55,
    "attack": 70,
    "defense": 45,
    "specialAttack": 70,
    "specialDefense": 50,
    "speed": 60,
    "total": 350
  },
  {
    "index": 59,
    "name": "ウインディ",
    "type1": "ほのお",
    "type2": "",
    "Ability1": "いかく",
    "Ability2": "もらいび",
    "Ability3": "",
    "HiddenAbility": "せいぎのこころ",
    "hp": 90,
    "attack": 110,
    "defense": 80,
    "specialAttack": 100,
    "specialDefense": 80,
    "speed": 95,
    "total": 555
  },
  {
    "index": 60,
    "name": "ニョロモ",
    "type1": "みず",
    "type2": "",
    "Ability1": "ちょすい",
    "Ability2": "しめりけ",
    "Ability3": "",
    "HiddenAbility": "すいすい",
    "hp": 40,
    "attack": 50,
    "defense": 40,
    "specialAttack": 40,
    "specialDefense": 40,
    "speed": 90,
    "total": 300
  },
  {
    "index": 61,
    "name": "ニョロゾ",
    "type1": "みず",
    "type2": "",
    "Ability1": "ちょすい",
    "Ability2": "しめりけ",
    "Ability3": "",
    "HiddenAbility": "すいすい",
    "hp": 65,
    "attack": 65,
    "defense": 65,
    "specialAttack": 50,
    "specialDefense": 50,
    "speed": 90,
    "total": 385
  },
  {
    "index": 62,
    "name": "ニョロボン",
    "type1": "みず",
    "type2": "かくとう",
    "Ability1": "ちょすい",
    "Ability2": "しめりけ",
    "Ability3": "",
    "HiddenAbility": "すいすい",
    "hp": 90,
    "attack": 95,
    "defense": 95,
    "specialAttack": 70,
    "specialDefense": 90,
    "speed": 70,
    "total": 510
  },
  {
    "index": 63,
    "name": "ケーシィ",
    "type1": "エスパー",
    "type2": "",
    "Ability1": "シンクロ",
    "Ability2": "せいしんりょく",
    "Ability3": "",
    "HiddenAbility": "マジックガード",
    "hp": 25,
    "attack": 20,
    "defense": 15,
    "specialAttack": 105,
    "specialDefense": 55,
    "speed": 90,
    "total": 310
  },
  {
    "index": 64,
    "name": "ユンゲラー",
    "type1": "エスパー",
    "type2": "",
    "Ability1": "シンクロ",
    "Ability2": "せいしんりょく",
    "Ability3": "",
    "HiddenAbility": "マジックガード",
    "hp": 40,
    "attack": 35,
    "defense": 30,
    "specialAttack": 120,
    "specialDefense": 70,
    "speed": 105,
    "total": 400
  },
  {
    "index": 65,
    "name": "フーディン",
    "type1": "エスパー",
    "type2": "",
    "Ability1": "シンクロ",
    "Ability2": "せいしんりょく",
    "Ability3": "",
    "HiddenAbility": "マジックガード",
    "hp": 55,
    "attack": 50,
    "defense": 45,
    "specialAttack": 135,
    "specialDefense": 95,
    "speed": 120,
    "total": 500
  },
  {
    "index": 66,
    "name": "ワンリキー",
    "type1": "かくとう",
    "type2": "",
    "Ability1": "こんじょう",
    "Ability2": "ノーガード",
    "Ability3": "",
    "HiddenAbility": "ふくつのこころ",
    "hp": 70,
    "attack": 80,
    "defense": 50,
    "specialAttack": 35,
    "specialDefense": 35,
    "speed": 35,
    "total": 305
  },
  {
    "index": 67,
    "name": "ゴーリキー",
    "type1": "かくとう",
    "type2": "",
    "Ability1": "こんじょう",
    "Ability2": "ノーガード",
    "Ability3": "",
    "HiddenAbility": "ふくつのこころ",
    "hp": 80,
    "attack": 100,
    "defense": 70,
    "specialAttack": 50,
    "specialDefense": 60,
    "speed": 45,
    "total": 405
  },
  {
    "index": 68,
    "name": "カイリキー",
    "type1": "かくとう",
    "type2": "",
    "Ability1": "こんじょう",
    "Ability2": "ノーガード",
    "Ability3": "",
    "HiddenAbility": "ふくつのこころ",
    "hp": 90,
    "attack": 130,
    "defense": 80,
    "specialAttack": 65,
    "specialDefense": 85,
    "speed": 55,
    "total": 505
  },
  {
    "index": 69,
    "name": "マダツボミ",
    "type1": "くさ",
    "type2": "どく",
    "Ability1": "ようりょくそ",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "くいしんぼう",
    "hp": 50,
    "attack": 75,
    "defense": 35,
    "specialAttack": 70,
    "specialDefense": 30,
    "speed": 40,
    "total": 300
  },
  {
    "index": 70,
    "name": "ウツドン",
    "type1": "くさ",
    "type2": "どく",
    "Ability1": "ようりょくそ",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "くいしんぼう",
    "hp": 65,
    "attack": 90,
    "defense": 50,
    "specialAttack": 85,
    "specialDefense": 45,
    "speed": 55,
    "total": 390
  },
  {
    "index": 71,
    "name": "ウツボット",
    "type1": "くさ",
    "type2": "どく",
    "Ability1": "ようりょくそ",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "くいしんぼう",
    "hp": 80,
    "attack": 105,
    "defense": 65,
    "specialAttack": 100,
    "specialDefense": 70,
    "speed": 70,
    "total": 490
  },
  {
    "index": 72,
    "name": "メノクラゲ",
    "type1": "みず",
    "type2": "どく",
    "Ability1": "クリアボディ",
    "Ability2": "ヘドロえき",
    "Ability3": "",
    "HiddenAbility": "あめうけざら",
    "hp": 40,
    "attack": 40,
    "defense": 35,
    "specialAttack": 50,
    "specialDefense": 100,
    "speed": 70,
    "total": 335
  },
  {
    "index": 73,
    "name": "ドククラゲ",
    "type1": "みず",
    "type2": "どく",
    "Ability1": "クリアボディ",
    "Ability2": "ヘドロえき",
    "Ability3": "",
    "HiddenAbility": "あめうけざら",
    "hp": 80,
    "attack": 70,
    "defense": 65,
    "specialAttack": 80,
    "specialDefense": 120,
    "speed": 100,
    "total": 515
  },
  {
    "index": 74,
    "name": "イシツブテ",
    "type1": "いわ",
    "type2": "じめん",
    "Ability1": "いしあたま",
    "Ability2": "がんじょう",
    "Ability3": "",
    "HiddenAbility": "すながくれ",
    "hp": 40,
    "attack": 80,
    "defense": 100,
    "specialAttack": 30,
    "specialDefense": 30,
    "speed": 20,
    "total": 300
  },
  {
    "index": 75,
    "name": "ゴローン",
    "type1": "いわ",
    "type2": "じめん",
    "Ability1": "いしあたま",
    "Ability2": "がんじょう",
    "Ability3": "",
    "HiddenAbility": "すながくれ",
    "hp": 55,
    "attack": 95,
    "defense": 115,
    "specialAttack": 45,
    "specialDefense": 45,
    "speed": 35,
    "total": 390
  },
  {
    "index": 76,
    "name": "ゴローニャ",
    "type1": "いわ",
    "type2": "じめん",
    "Ability1": "いしあたま",
    "Ability2": "がんじょう",
    "Ability3": "",
    "HiddenAbility": "すながくれ",
    "hp": 80,
    "attack": 120,
    "defense": 130,
    "specialAttack": 55,
    "specialDefense": 65,
    "speed": 45,
    "total": 495
  },
  {
    "index": 77,
    "name": "ポニータ",
    "type1": "ほのお",
    "type2": "",
    "Ability1": "にげあし",
    "Ability2": "もらいび",
    "Ability3": "",
    "HiddenAbility": "ほのおのからだ",
    "hp": 50,
    "attack": 85,
    "defense": 55,
    "specialAttack": 65,
    "specialDefense": 65,
    "speed": 90,
    "total": 410
  },
  {
    "index": 78,
    "name": "ギャロップ",
    "type1": "ほのお",
    "type2": "",
    "Ability1": "にげあし",
    "Ability2": "もらいび",
    "Ability3": "",
    "HiddenAbility": "ほのおのからだ",
    "hp": 65,
    "attack": 100,
    "defense": 70,
    "specialAttack": 80,
    "specialDefense": 80,
    "speed": 105,
    "total": 500
  },
  {
    "index": 79,
    "name": "ヤドン",
    "type1": "みず",
    "type2": "エスパー",
    "Ability1": "どんかん",
    "Ability2": "マイペース",
    "Ability3": "",
    "HiddenAbility": "さいせいりょく",
    "hp": 90,
    "attack": 65,
    "defense": 65,
    "specialAttack": 40,
    "specialDefense": 40,
    "speed": 15,
    "total": 315
  },
  {
    "index": 80,
    "name": "ヤドラン",
    "type1": "みず",
    "type2": "エスパー",
    "Ability1": "どんかん",
    "Ability2": "マイペース",
    "Ability3": "",
    "HiddenAbility": "さいせいりょく",
    "hp": 95,
    "attack": 75,
    "defense": 110,
    "specialAttack": 100,
    "specialDefense": 80,
    "speed": 30,
    "total": 490
  },
  {
    "index": 81,
    "name": "コイル",
    "type1": "でんき",
    "type2": "はがね",
    "Ability1": "じりょく",
    "Ability2": "がんじょう",
    "Ability3": "",
    "HiddenAbility": "アナライズ",
    "hp": 25,
    "attack": 35,
    "defense": 70,
    "specialAttack": 95,
    "specialDefense": 55,
    "speed": 45,
    "total": 325
  },
  {
    "index": 82,
    "name": "レアコイル",
    "type1": "でんき",
    "type2": "はがね",
    "Ability1": "じりょく",
    "Ability2": "がんじょう",
    "Ability3": "",
    "HiddenAbility": "アナライズ",
    "hp": 50,
    "attack": 60,
    "defense": 95,
    "specialAttack": 120,
    "specialDefense": 70,
    "speed": 70,
    "total": 465
  },
  {
    "index": 83,
    "name": "カモネギ",
    "type1": "ノーマル",
    "type2": "ひこう",
    "Ability1": "するどいめ",
    "Ability2": "せいしんりょく",
    "Ability3": "",
    "HiddenAbility": "まけんき",
    "hp": 52,
    "attack": 90,
    "defense": 55,
    "specialAttack": 58,
    "specialDefense": 62,
    "speed": 60,
    "total": 377
  },
  {
    "index": 84,
    "name": "ドードー",
    "type1": "ノーマル",
    "type2": "ひこう",
    "Ability1": "にげあし",
    "Ability2": "はやおき",
    "Ability3": "",
    "HiddenAbility": "ちどりあし",
    "hp": 35,
    "attack": 85,
    "defense": 45,
    "specialAttack": 35,
    "specialDefense": 35,
    "speed": 75,
    "total": 310
  },
  {
    "index": 85,
    "name": "ドードリオ",
    "type1": "ノーマル",
    "type2": "ひこう",
    "Ability1": "にげあし",
    "Ability2": "はやおき",
    "Ability3": "",
    "HiddenAbility": "ちどりあし",
    "hp": 60,
    "attack": 110,
    "defense": 70,
    "specialAttack": 60,
    "specialDefense": 60,
    "speed": 110,
    "total": 470
  },
  {
    "index": 86,
    "name": "パウワウ",
    "type1": "みず",
    "type2": "",
    "Ability1": "あついしぼう",
    "Ability2": "うるおいボディ",
    "Ability3": "",
    "HiddenAbility": "アイスボディ",
    "hp": 65,
    "attack": 45,
    "defense": 55,
    "specialAttack": 45,
    "specialDefense": 70,
    "speed": 45,
    "total": 325
  },
  {
    "index": 87,
    "name": "ジュゴン",
    "type1": "みず",
    "type2": "こおり",
    "Ability1": "あついしぼう",
    "Ability2": "うるおいボディ",
    "Ability3": "",
    "HiddenAbility": "アイスボディ",
    "hp": 90,
    "attack": 70,
    "defense": 80,
    "specialAttack": 70,
    "specialDefense": 95,
    "speed": 70,
    "total": 475
  },
  {
    "index": 88,
    "name": "ベトベター",
    "type1": "どく",
    "type2": "",
    "Ability1": "あくしゅう",
    "Ability2": "ねんちゃく",
    "Ability3": "",
    "HiddenAbility": "どくしゅ",
    "hp": 80,
    "attack": 80,
    "defense": 50,
    "specialAttack": 40,
    "specialDefense": 50,
    "speed": 25,
    "total": 325
  },
  {
    "index": 89,
    "name": "ベトベトン",
    "type1": "どく",
    "type2": "",
    "Ability1": "あくしゅう",
    "Ability2": "ねんちゃく",
    "Ability3": "",
    "HiddenAbility": "どくしゅ",
    "hp": 105,
    "attack": 105,
    "defense": 75,
    "specialAttack": 65,
    "specialDefense": 100,
    "speed": 50,
    "total": 500
  },
  {
    "index": 90,
    "name": "シェルダー",
    "type1": "みず",
    "type2": "",
    "Ability1": "シェルアーマー",
    "Ability2": "スキルリンク",
    "Ability3": "",
    "HiddenAbility": "ぼうじん",
    "hp": 30,
    "attack": 65,
    "defense": 100,
    "specialAttack": 45,
    "specialDefense": 25,
    "speed": 40,
    "total": 305
  },
  {
    "index": 91,
    "name": "パルシェン",
    "type1": "みず",
    "type2": "こおり",
    "Ability1": "シェルアーマー",
    "Ability2": "スキルリンク",
    "Ability3": "",
    "HiddenAbility": "ぼうじん",
    "hp": 50,
    "attack": 95,
    "defense": 180,
    "specialAttack": 85,
    "specialDefense": 45,
    "speed": 70,
    "total": 525
  },
  {
    "index": 92,
    "name": "ゴース",
    "type1": "ゴースト",
    "type2": "どく",
    "Ability1": "ふゆう",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "",
    "hp": 30,
    "attack": 35,
    "defense": 30,
    "specialAttack": 100,
    "specialDefense": 35,
    "speed": 80,
    "total": 310
  },
  {
    "index": 93,
    "name": "ゴースト",
    "type1": "ゴースト",
    "type2": "どく",
    "Ability1": "ふゆう",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "",
    "hp": 45,
    "attack": 50,
    "defense": 45,
    "specialAttack": 115,
    "specialDefense": 55,
    "speed": 95,
    "total": 405
  },
  {
    "index": 94,
    "name": "ゲンガー",
    "type1": "ゴースト",
    "type2": "どく",
    "Ability1": "のろわれボディ",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "",
    "hp": 60,
    "attack": 65,
    "defense": 60,
    "specialAttack": 130,
    "specialDefense": 75,
    "speed": 110,
    "total": 500
  },
  {
    "index": 95,
    "name": "イワーク",
    "type1": "いわ",
    "type2": "じめん",
    "Ability1": "いしあたま",
    "Ability2": "がんじょう",
    "Ability3": "",
    "HiddenAbility": "くだけるよろい",
    "hp": 35,
    "attack": 45,
    "defense": 160,
    "specialAttack": 30,
    "specialDefense": 45,
    "speed": 70,
    "total": 385
  },
  {
    "index": 96,
    "name": "スリープ",
    "type1": "エスパー",
    "type2": "",
    "Ability1": "ふみん",
    "Ability2": "よちむ",
    "Ability3": "",
    "HiddenAbility": "せいしんりょく",
    "hp": 60,
    "attack": 48,
    "defense": 45,
    "specialAttack": 43,
    "specialDefense": 90,
    "speed": 42,
    "total": 328
  },
  {
    "index": 97,
    "name": "スリーパー",
    "type1": "エスパー",
    "type2": "",
    "Ability1": "ふみん",
    "Ability2": "よちむ",
    "Ability3": "",
    "HiddenAbility": "せいしんりょく",
    "hp": 85,
    "attack": 73,
    "defense": 70,
    "specialAttack": 73,
    "specialDefense": 115,
    "speed": 67,
    "total": 483
  },
  {
    "index": 98,
    "name": "クラブ",
    "type1": "みず",
    "type2": "",
    "Ability1": "かいりきバサミ",
    "Ability2": "シェルアーマー",
    "Ability3": "",
    "HiddenAbility": "ちからずく",
    "hp": 30,
    "attack": 105,
    "defense": 90,
    "specialAttack": 25,
    "specialDefense": 25,
    "speed": 50,
    "total": 325
  },
  {
    "index": 99,
    "name": "キングラー",
    "type1": "みず",
    "type2": "",
    "Ability1": "かいりきバサミ",
    "Ability2": "シェルアーマー",
    "Ability3": "",
    "HiddenAbility": "ちからずく",
    "hp": 55,
    "attack": 130,
    "defense": 115,
    "specialAttack": 50,
    "specialDefense": 50,
    "speed": 75,
    "total": 475
  },
  {
    "index": 100,
    "name": "ビリリダマ",
    "type1": "でんき",
    "type2": "",
    "Ability1": "ぼうおん",
    "Ability2": "せいでんき",
    "Ability3": "",
    "HiddenAbility": "ゆうばく",
    "hp": 40,
    "attack": 30,
    "defense": 50,
    "specialAttack": 55,
    "specialDefense": 55,
    "speed": 100,
    "total": 330
  },
  {
    "index": 101,
    "name": "マルマイン",
    "type1": "でんき",
    "type2": "",
    "Ability1": "ぼうおん",
    "Ability2": "せいでんき",
    "Ability3": "",
    "HiddenAbility": "ゆうばく",
    "hp": 60,
    "attack": 50,
    "defense": 70,
    "specialAttack": 80,
    "specialDefense": 80,
    "speed": 150,
    "total": 490
  },
  {
    "index": 102,
    "name": "タマタマ",
    "type1": "くさ",
    "type2": "エスパー",
    "Ability1": "ようりょくそ",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "しゅうかく",
    "hp": 60,
    "attack": 40,
    "defense": 80,
    "specialAttack": 60,
    "specialDefense": 45,
    "speed": 40,
    "total": 325
  },
  {
    "index": 103,
    "name": "ナッシー",
    "type1": "くさ",
    "type2": "エスパー",
    "Ability1": "ようりょくそ",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "しゅうかく",
    "hp": 95,
    "attack": 95,
    "defense": 85,
    "specialAttack": 125,
    "specialDefense": 75,
    "speed": 55,
    "total": 530
  },
  {
    "index": 104,
    "name": "カラカラ",
    "type1": "じめん",
    "type2": "",
    "Ability1": "いしあたま",
    "Ability2": "ひらいしん",
    "Ability3": "",
    "HiddenAbility": "カブトアーマー",
    "hp": 50,
    "attack": 50,
    "defense": 95,
    "specialAttack": 40,
    "specialDefense": 50,
    "speed": 35,
    "total": 320
  },
  {
    "index": 105,
    "name": "ガラガラ",
    "type1": "じめん",
    "type2": "",
    "Ability1": "いしあたま",
    "Ability2": "ひらいしん",
    "Ability3": "",
    "HiddenAbility": "カブトアーマー",
    "hp": 60,
    "attack": 80,
    "defense": 110,
    "specialAttack": 50,
    "specialDefense": 80,
    "speed": 45,
    "total": 425
  },
  {
    "index": 106,
    "name": "サワムラー",
    "type1": "かくとう",
    "type2": "",
    "Ability1": "じゅうなん",
    "Ability2": "すてみ",
    "Ability3": "",
    "HiddenAbility": "かるわざ",
    "hp": 50,
    "attack": 120,
    "defense": 53,
    "specialAttack": 35,
    "specialDefense": 110,
    "speed": 87,
    "total": 455
  },
  {
    "index": 107,
    "name": "エビワラー",
    "type1": "かくとう",
    "type2": "",
    "Ability1": "するどいめ",
    "Ability2": "てつのこぶし",
    "Ability3": "",
    "HiddenAbility": "せいしんりょく",
    "hp": 50,
    "attack": 105,
    "defense": 79,
    "specialAttack": 35,
    "specialDefense": 110,
    "speed": 76,
    "total": 455
  },
  {
    "index": 108,
    "name": "ベロリンガ",
    "type1": "ノーマル",
    "type2": "",
    "Ability1": "マイペース",
    "Ability2": "どんかん",
    "Ability3": "",
    "HiddenAbility": "ノーてんき",
    "hp": 90,
    "attack": 55,
    "defense": 75,
    "specialAttack": 60,
    "specialDefense": 75,
    "speed": 30,
    "total": 385
  },
  {
    "index": 109,
    "name": "ドガース",
    "type1": "どく",
    "type2": "",
    "Ability1": "ふゆう",
    "Ability2": "かがくへんかガス",
    "Ability3": "",
    "HiddenAbility": "あくしゅう",
    "hp": 40,
    "attack": 65,
    "defense": 95,
    "specialAttack": 60,
    "specialDefense": 45,
    "speed": 35,
    "total": 340
  },
  {
    "index": 110,
    "name": "マタドガス",
    "type1": "どく",
    "type2": "",
    "Ability1": "ふゆう",
    "Ability2": "かがくへんかガス",
    "Ability3": "",
    "HiddenAbility": "あくしゅう",
    "hp": 65,
    "attack": 90,
    "defense": 120,
    "specialAttack": 85,
    "specialDefense": 70,
    "speed": 60,
    "total": 490
  },
  {
    "index": 111,
    "name": "サイホーン",
    "type1": "じめん",
    "type2": "いわ",
    "Ability1": "ひらいしん",
    "Ability2": "いしあたま",
    "Ability3": "",
    "HiddenAbility": "すてみ",
    "hp": 80,
    "attack": 85,
    "defense": 95,
    "specialAttack": 30,
    "specialDefense": 30,
    "speed": 25,
    "total": 345
  },
  {
    "index": 112,
    "name": "サイドン",
    "type1": "じめん",
    "type2": "いわ",
    "Ability1": "ひらいしん",
    "Ability2": "いしあたま",
    "Ability3": "",
    "HiddenAbility": "すてみ",
    "hp": 105,
    "attack": 130,
    "defense": 120,
    "specialAttack": 45,
    "specialDefense": 45,
    "speed": 40,
    "total": 485
  },
  {
    "index": 113,
    "name": "ラッキー",
    "type1": "ノーマル",
    "type2": "",
    "Ability1": "しぜんかいふく",
    "Ability2": "てんのめぐみ",
    "Ability3": "",
    "HiddenAbility": "いやしのこころ",
    "hp": 250,
    "attack": 5,
    "defense": 5,
    "specialAttack": 35,
    "specialDefense": 105,
    "speed": 50,
    "total": 450
  },
  {
    "index": 114,
    "name": "モンジャラ",
    "type1": "くさ",
    "type2": "",
    "Ability1": "ようりょくそ",
    "Ability2": "リーフガード",
    "Ability3": "",
    "HiddenAbility": "さいせいりょく",
    "hp": 65,
    "attack": 55,
    "defense": 115,
    "specialAttack": 100,
    "specialDefense": 40,
    "speed": 60,
    "total": 435
  },
  {
    "index": 115,
    "name": "ガルーラ",
    "type1": "ノーマル",
    "type2": "",
    "Ability1": "はやおき",
    "Ability2": "きもったま",
    "Ability3": "",
    "HiddenAbility": "せいしんりょく",
    "hp": 105,
    "attack": 95,
    "defense": 80,
    "specialAttack": 40,
    "specialDefense": 80,
    "speed": 90,
    "total": 490
  },
  {
    "index": 116,
    "name": "タッツー",
    "type1": "みず",
    "type2": "",
    "Ability1": "すいすい",
    "Ability2": "スナイパー",
    "Ability3": "",
    "HiddenAbility": "しめりけ",
    "hp": 30,
    "attack": 40,
    "defense": 70,
    "specialAttack": 70,
    "specialDefense": 25,
    "speed": 60,
    "total": 295
  },
  {
    "index": 117,
    "name": "シードラ",
    "type1": "みず",
    "type2": "",
    "Ability1": "どくのトゲ",
    "Ability2": "スナイパー",
    "Ability3": "",
    "HiddenAbility": "しめりけ",
    "hp": 55,
    "attack": 65,
    "defense": 95,
    "specialAttack": 95,
    "specialDefense": 45,
    "speed": 85,
    "total": 440
  },
  {
    "index": 118,
    "name": "トサキント",
    "type1": "みず",
    "type2": "",
    "Ability1": "すいすい",
    "Ability2": "みずのベール",
    "Ability3": "",
    "HiddenAbility": "ひらいしん",
    "hp": 45,
    "attack": 67,
    "defense": 60,
    "specialAttack": 35,
    "specialDefense": 50,
    "speed": 63,
    "total": 320
  },
  {
    "index": 119,
    "name": "アズマオウ",
    "type1": "みず",
    "type2": "",
    "Ability1": "すいすい",
    "Ability2": "みずのベール",
    "Ability3": "",
    "HiddenAbility": "ひらいしん",
    "hp": 80,
    "attack": 92,
    "defense": 65,
    "specialAttack": 65,
    "specialDefense": 80,
    "speed": 68,
    "total": 450
  },
  {
    "index": 120,
    "name": "ヒトデマン",
    "type1": "みず",
    "type2": "",
    "Ability1": "はっこう",
    "Ability2": "しぜんかいふく",
    "Ability3": "",
    "HiddenAbility": "アナライズ",
    "hp": 30,
    "attack": 45,
    "defense": 55,
    "specialAttack": 70,
    "specialDefense": 55,
    "speed": 85,
    "total": 340
  },
  {
    "index": 121,
    "name": "スターミー",
    "type1": "みず",
    "type2": "エスパー",
    "Ability1": "はっこう",
    "Ability2": "しぜんかいふく",
    "Ability3": "",
    "HiddenAbility": "アナライズ",
    "hp": 60,
    "attack": 75,
    "defense": 85,
    "specialAttack": 100,
    "specialDefense": 85,
    "speed": 115,
    "total": 520
  },
  {
    "index": 122,
    "name": "バリヤード",
    "type1": "エスパー",
    "type2": "フェアリー",
    "Ability1": "ぼうおん",
    "Ability2": "フィルター",
    "Ability3": "",
    "HiddenAbility": "テクニシャン",
    "hp": 40,
    "attack": 45,
    "defense": 65,
    "specialAttack": 100,
    "specialDefense": 120,
    "speed": 90,
    "total": 460
  },
  {
    "index": 123,
    "name": "ストライク",
    "type1": "むし",
    "type2": "ひこう",
    "Ability1": "むしのしらせ",
    "Ability2": "テクニシャン",
    "Ability3": "",
    "HiddenAbility": "ふくつのこころ",
    "hp": 70,
    "attack": 110,
    "defense": 80,
    "specialAttack": 55,
    "specialDefense": 80,
    "speed": 105,
    "total": 500
  },
  {
    "index": 124,
    "name": "ルージュラ",
    "type1": "こおり",
    "type2": "エスパー",
    "Ability1": "どんかん",
    "Ability2": "よちむ",
    "Ability3": "",
    "HiddenAbility": "かんそうはだ",
    "hp": 65,
    "attack": 50,
    "defense": 35,
    "specialAttack": 115,
    "specialDefense": 95,
    "speed": 95,
    "total": 455
  },
  {
    "index": 125,
    "name": "エレブー",
    "type1": "でんき",
    "type2": "",
    "Ability1": "せいでんき",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "やるき",
    "hp": 65,
    "attack": 83,
    "defense": 57,
    "specialAttack": 95,
    "specialDefense": 85,
    "speed": 105,
    "total": 490
  },
  {
    "index": 126,
    "name": "ブーバー",
    "type1": "ほのお",
    "type2": "",
    "Ability1": "ほのおのからだ",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "やるき",
    "hp": 65,
    "attack": 95,
    "defense": 57,
    "specialAttack": 100,
    "specialDefense": 85,
    "speed": 93,
    "total": 495
  },
  {
    "index": 127,
    "name": "カイロス",
    "type1": "むし",
    "type2": "",
    "Ability1": "かいりきバサミ",
    "Ability2": "かたやぶり",
    "Ability3": "",
    "HiddenAbility": "じしんかじょう",
    "hp": 65,
    "attack": 125,
    "defense": 100,
    "specialAttack": 55,
    "specialDefense": 70,
    "speed": 85,
    "total": 500
  },
  {
    "index": 128,
    "name": "ケンタロス",
    "type1": "ノーマル",
    "type2": "",
    "Ability1": "いかく",
    "Ability2": "いかりのつぼ",
    "Ability3": "",
    "HiddenAbility": "ちからずく",
    "hp": 75,
    "attack": 100,
    "defense": 95,
    "specialAttack": 40,
    "specialDefense": 70,
    "speed": 110,
    "total": 490
  },
  {
    "index": 129,
    "name": "コイキング",
    "type1": "みず",
    "type2": "",
    "Ability1": "すいすい",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "びびり",
    "hp": 20,
    "attack": 10,
    "defense": 55,
    "specialAttack": 15,
    "specialDefense": 20,
    "speed": 80,
    "total": 200
  },
  {
    "index": 130,
    "name": "ギャラドス",
    "type1": "みず",
    "type2": "ひこう",
    "Ability1": "いかく",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "じしんかじょう",
    "hp": 95,
    "attack": 125,
    "defense": 79,
    "specialAttack": 60,
    "specialDefense": 100,
    "speed": 81,
    "total": 540
  },
  {
    "index": 131,
    "name": "ラプラス",
    "type1": "みず",
    "type2": "こおり",
    "Ability1": "ちょすい",
    "Ability2": "シェルアーマー",
    "Ability3": "",
    "HiddenAbility": "うるおいボディ",
    "hp": 130,
    "attack": 85,
    "defense": 80,
    "specialAttack": 85,
    "specialDefense": 95,
    "speed": 60,
    "total": 535
  },
  {
    "index": 132,
    "name": "メタモン",
    "type1": "ノーマル",
    "type2": "",
    "Ability1": "じゅうなん",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "かわりもの",
    "hp": 48,
    "attack": 48,
    "defense": 48,
    "specialAttack": 48,
    "specialDefense": 48,
    "speed": 48,
    "total": 288
  },
  {
    "index": 133,
    "name": "イーブイ",
    "type1": "ノーマル",
    "type2": "",
    "Ability1": "にげあし",
    "Ability2": "てきおうりょく",
    "Ability3": "",
    "HiddenAbility": "きけんよち",
    "hp": 55,
    "attack": 55,
    "defense": 50,
    "specialAttack": 45,
    "specialDefense": 65,
    "speed": 55,
    "total": 325
  },
  {
    "index": 134,
    "name": "シャワーズ",
    "type1": "みず",
    "type2": "",
    "Ability1": "ちょすい",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "うるおいボディ",
    "hp": 130,
    "attack": 65,
    "defense": 60,
    "specialAttack": 110,
    "specialDefense": 95,
    "speed": 65,
    "total": 525
  },
  {
    "index": 135,
    "name": "サンダース",
    "type1": "でんき",
    "type2": "",
    "Ability1": "ちくでん",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "はやあし",
    "hp": 65,
    "attack": 65,
    "defense": 60,
    "specialAttack": 110,
    "specialDefense": 95,
    "speed": 130,
    "total": 525
  },
  {
    "index": 136,
    "name": "ブースター",
    "type1": "ほのお",
    "type2": "",
    "Ability1": "もらいび",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "こんじょう",
    "hp": 65,
    "attack": 130,
    "defense": 60,
    "specialAttack": 95,
    "specialDefense": 110,
    "speed": 65,
    "total": 525
  },
  {
    "index": 137,
    "name": "ポリゴン",
    "type1": "ノーマル",
    "type2": "",
    "Ability1": "トレース",
    "Ability2": "ダウンロード",
    "Ability3": "",
    "HiddenAbility": "アナライズ",
    "hp": 65,
    "attack": 60,
    "defense": 70,
    "specialAttack": 85,
    "specialDefense": 75,
    "speed": 40,
    "total": 395
  },
  {
    "index": 138,
    "name": "オムナイト",
    "type1": "いわ",
    "type2": "みず",
    "Ability1": "すいすい",
    "Ability2": "シェルアーマー",
    "Ability3": "",
    "HiddenAbility": "くだけるよろい",
    "hp": 35,
    "attack": 40,
    "defense": 100,
    "specialAttack": 90,
    "specialDefense": 55,
    "speed": 35,
    "total": 355
  },
  {
    "index": 139,
    "name": "オムスター",
    "type1": "いわ",
    "type2": "みず",
    "Ability1": "すいすい",
    "Ability2": "シェルアーマー",
    "Ability3": "",
    "HiddenAbility": "くだけるよろい",
    "hp": 70,
    "attack": 60,
    "defense": 125,
    "specialAttack": 115,
    "specialDefense": 70,
    "speed": 55,
    "total": 495
  },
  {
    "index": 140,
    "name": "カブト",
    "type1": "いわ",
    "type2": "みず",
    "Ability1": "すいすい",
    "Ability2": "カブトアーマー",
    "Ability3": "",
    "HiddenAbility": "くだけるよろい",
    "hp": 30,
    "attack": 80,
    "defense": 90,
    "specialAttack": 55,
    "specialDefense": 45,
    "speed": 55,
    "total": 355
  },
  {
    "index": 141,
    "name": "カブトプス",
    "type1": "いわ",
    "type2": "みず",
    "Ability1": "すいすい",
    "Ability2": "カブトアーマー",
    "Ability3": "",
    "HiddenAbility": "くだけるよろい",
    "hp": 60,
    "attack": 115,
    "defense": 105,
    "specialAttack": 65,
    "specialDefense": 70,
    "speed": 80,
    "total": 495
  },
  {
    "index": 142,
    "name": "プテラ",
    "type1": "いわ",
    "type2": "ひこう",
    "Ability1": "いしあたま",
    "Ability2": "プレッシャー",
    "Ability3": "",
    "HiddenAbility": "きんちょうかん",
    "hp": 80,
    "attack": 105,
    "defense": 65,
    "specialAttack": 60,
    "specialDefense": 75,
    "speed": 130,
    "total": 515
  },
  {
    "index": 143,
    "name": "カビゴン",
    "type1": "ノーマル",
    "type2": "",
    "Ability1": "めんえき",
    "Ability2": "あついしぼう",
    "Ability3": "",
    "HiddenAbility": "くいしんぼう",
    "hp": 160,
    "attack": 110,
    "defense": 65,
    "specialAttack": 65,
    "specialDefense": 110,
    "speed": 30,
    "total": 540
  },
  {
    "index": 144,
    "name": "フリーザー",
    "type1": "こおり",
    "type2": "ひこう",
    "Ability1": "プレッシャー",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "ゆきがくれ",
    "hp": 90,
    "attack": 85,
    "defense": 100,
    "specialAttack": 95,
    "specialDefense": 125,
    "speed": 85,
    "total": 580
  },
  {
    "index": 145,
    "name": "サンダー",
    "type1": "でんき",
    "type2": "ひこう",
    "Ability1": "プレッシャー",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "せいでんき",
    "hp": 90,
    "attack": 90,
    "defense": 85,
    "specialAttack": 125,
    "specialDefense": 90,
    "speed": 100,
    "total": 580
  },
  {
    "index": 146,
    "name": "ファイヤー",
    "type1": "ほのお",
    "type2": "ひこう",
    "Ability1": "プレッシャー",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "ほのおのからだ",
    "hp": 90,
    "attack": 100,
    "defense": 90,
    "specialAttack": 125,
    "specialDefense": 85,
    "speed": 90,
    "total": 580
  },
  {
    "index": 147,
    "name": "ミニリュウ",
    "type1": "ドラゴン",
    "type2": "",
    "Ability1": "だっぴ",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "ふしぎなうろこ",
    "hp": 41,
    "attack": 64,
    "defense": 45,
    "specialAttack": 50,
    "specialDefense": 50,
    "speed": 50,
    "total": 300
  },
  {
    "index": 148,
    "name": "ハクリュー",
    "type1": "ドラゴン",
    "type2": "",
    "Ability1": "だっぴ",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "ふしぎなうろこ",
    "hp": 61,
    "attack": 84,
    "defense": 65,
    "specialAttack": 70,
    "specialDefense": 70,
    "speed": 70,
    "total": 420
  },
  {
    "index": 149,
    "name": "カイリュー",
    "type1": "ドラゴン",
    "type2": "ひこう",
    "Ability1": "せいしんりょく",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "マルチスケイル",
    "hp": 91,
    "attack": 134,
    "defense": 95,
    "specialAttack": 100,
    "specialDefense": 100,
    "speed": 80,
    "total": 600
  },
  {
    "index": 150,
    "name": "ミュウツー",
    "type1": "エスパー",
    "type2": "",
    "Ability1": "プレッシャー",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "きんちょうかん",
    "hp": 106,
    "attack": 110,
    "defense": 90,
    "specialAttack": 154,
    "specialDefense": 90,
    "speed": 130,
    "total": 680
  },
  {
    "index": 151,
    "name": "ミュウ",
    "type1": "エスパー",
    "type2": "",
    "Ability1": "シンクロ",
    "Ability2": "",
    "Ability3": "",
    "HiddenAbility": "",
    "hp": 100,
    "attack": 100,
    "defense": 100,
    "specialAttack": 100,
    "specialDefense": 100,
    "speed": 100,
    "total": 600
  }
];
